MyWebPage/ViewModels/ContactViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MyWebPage.Models
{
    public class ContactViewModel
    {
        public String Email { get; set; }
        public String Name { get; set; }
        public String Subject { get; set; }
        public String Message { get; set; }
    }
}

MyWebPage/Controllers/ContactController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Identity.UI.Services;
using Microsoft.AspNetCore.Mvc;
using MyWebPage.Models;

namespace MyWebPage.Controllers
{
    public class ContactController : Controller
    {
        private readonly IEmailSender _emailSender;

        public ContactController(IEmailSender emailSender)
        {
            _emailSender = emailSender;
        }

        [HttpPost]
        public async Task<IActionResult> SendMail(ContactViewModel contactViewModel)
        {
            string msg = $"{contactViewModel.Name} {Environment.NewLine}  {contactViewModel.Message}";
            await _emailSender.SendEmailAsync(contactViewModel.Email, $"{contactViewModel.Email} - {contactViewModel.Subject}", msg);
            TempData["ConfirmMsg"] = "Dziękuję za wysłanie wiadomości";
            return RedirectToAction("Index", "Home");
        }
    }
}

MyWebPage/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Globalization;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity.UI.Services;
using Microsoft.AspNetCore.Localization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using MyWebPage.Models;
using MyWebPage.Services;

namespace MyWebPage.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private readonly FileService _fileService;


        public HomeController(ILogger<HomeController> logger, FileService fileService)
        {
            _logger = logger;
            _fileService = fileService;
            
        }

        public IActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public IActionResult GetCV(String language)
        {
            String filePath;
            if (language.Equals("PL"))
            {
                filePath = "Content/About/CVs/CV_PL.pdf";
            }
            else
            {
                filePath = "Content/About/CVs/CV_EN.pdf";
            }
            if(filePath == null)
            {
                return NotFound();
            }
            return _fileService.GetFileAsStream(filePath) ?? (IActionResult)NotFound();
        }

        public IActionResult ChangeCulture(string language)
        {
            HttpContext.Response.Cookies.Append(
                            CookieRequestCultureProvider.DefaultCookieName,
                            CookieRequestCultureProvider.MakeCookieValue(new RequestCulture(language)));

            return RedirectToAction("Index", new { culture = language }) ;
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

MyWebPage/ViewComponents/ProjectsViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using MyWebPage.Data;
using MyWebPage.Repositories;
using MyWebPage.Repositories.Interfaces;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MyWebPage.ViewComponents
{
    [ViewComponent(Name = "Projects")]
    public class ProjectsViewComponent : ViewComponent
    {
        public IProjectRepository projectRepository;

        public ProjectsViewComponent(IProjectRepository projectRepository)
        {
            this.projectRepository = projectRepository;
        }

        public async Task<IViewComponentResult> InvokeAsync()
        {
            var projects = await projectRepository.GetAll();

            return View(projects);
        }
    }
}

MyWebPage/Views/Home/About.cshtml
@using Microsoft.AspNetCore.Mvc.Localization
@using System.Globalization;

@inject IViewLocalizer Localizer
@inject Wangkanai.Detection.Services.IDetectionService DetectionService

<link rel="stylesheet" href="~/css/about.css?v=2" />
@{
    ViewData["Title"] = "O mnie";
    var requestCulture = CultureInfo.CurrentCulture;
    var regionInfo = new RegionInfo(requestCulture.Name);
}

@if (DetectionService.Device.Type != Wangkanai.Detection.Models.Device.Desktop)
{
    <div class="row">
        <div class="col">
            <h1 class="text-white display-3 text-center title">@Localizer["about_title"]</h1>
        </div>
    </div>
    <div class="row">
        <div class="col mb-0 pb-0" id="about_image_mobile">
            <img src="~/Content/About/Images/ja.png" class="d-block img-fluid" />
        </div>
    </div>
    <div class="row">
        <div class="col" style="background-color:rgba(0,0,0,0.4);">
            <p class="m-4 about_text_mobile" lang=@(regionInfo.TwoLetterISORegionName.Equals("PL") ? "pl" : "en")>
                @Localizer["about_text"]
            </p>
        </div>
    </div>
    <div class="row">
        <div class="col w-100"  style="background-color:rgba(0,0,0,0.4);">
            <div class="d-flex justify-content-center align-items-center container-fluid w-100 mb-3">
                <form method="get" class="form-inline" asp-controller="Home" asp-action="GetCV">
                    <div class="form-row align-items-center">
                        <label class=" h6 text-nowrap mr-3 mt-1">@Localizer["about_CV_language"]</label>
                        @if (@regionInfo.TwoLetterISORegionName == "US")
                        {
                            <select name="language" class="form-control form-control-sm" style="width:65px;">
                                <option>EN</option>
                                <option>PL</option>
                            </select>
                        }
                        else
                        {
                            <select name="language" class="form-control form-control-sm" style="width:60px;">
                                <option>PL</option>
                                <option>EN</option>
                            </select>
                        }
                        <button type="submit" class="btn btn-dark ml-1" style="transform:scale(0.75, 0.75);">@Localizer["about_button_download"]</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
}
else
{
    <div class="row">
        <div class="col">
            <h1 class="text-white display-1 text-center title">@Localizer["about_title"]</h1>
        </div>
    </div>
    <div id="about_text_row" class="row align-items-center">
        <div id="about_text_col" class="col">
            <div class="row">
                <p class="text-justify text-white" lang=@(regionInfo.TwoLetterISORegionName.Equals("PL") ? "pl" : "en")>
                    @Localizer["about_text"]
                </p>
            </div>
            <div class="row">
                <form method="get" class="form-inline w-100" asp-controller="Home" asp-action="GetCV">
                    <div class="form-group row">
                        <label for="staticEmail" class="h5 text-nowrap ml-3 mr-3">@Localizer["about_CV_language"]</label>
                        @if (@regionInfo.TwoLetterISORegionName == "US")
                        {
                            <select name="language" class="form-control form-control-sm">
                                <option>EN</option>
                                <option>PL</option>
                            </select>
                        }
                        else
                        {
                            <select name="language" class="form-control form-control-sm">
                                <option>PL</option>
                                <option>EN</option>
                            </select>
                        }
                        <button type="submit" class="btn btn-dark btn ml-1" style="transform:scale(0.8, 0.8);">@Localizer["about_button_download"]</button>

                    </div>
                </form>
            </div>
        </div>
        <div class="col" id="about_image_col">
            <img src="~/Content/About/Images/ja.png" class="d-block img-fluid" />
        </div>
    </div>

}

MyWebPage/Views/Home/Contact.cshtml
@using Microsoft.AspNetCore.Mvc.Localization
@using System.Globalization;

@inject IViewLocalizer Localizer
@inject Wangkanai.Detection.Services.IDetectionService DetectionService

@model ContactViewModel;

@{
    var requestCulture = CultureInfo.CurrentCulture;
    var regionInfo = new RegionInfo(requestCulture.Name);
}

<link rel="stylesheet" href="~/css/contact.css?v=2" />

@if (DetectionService.Device.Type != Wangkanai.Detection.Models.Device.Desktop)
{
<div class="container-fluid">
    <div class="row">
        <div class="col" id="section_title">
            <h1 class="text-white display-3 text-center title">@Localizer["contact_title"]</h1>
        </div>
    </div>
    <div class="row">
        <div class="modal fade" id="sendMailModal" tabindex="-1" aria-labelledby="sendMailModalLabel" aria-hidden="true">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="sendMailModalLabel">@Localizer["modal_header"]</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <div class="modal-body">
                        <form asp-controller="Contact" asp-action="SendMail" id="contact_form">
                            <div class="form-group">
                                <label asp-for="Email">@Localizer["modal_email_title"]</label>
                                <input asp-for="Email" type="email" class="form-control" aria-describedby="emailHelp" placeholder="@Localizer["modal_email_placeholder"]">
                                <small id="emailHelp" class="form-text text-muted">@Localizer["modal_email_described"]</small>
                                <span asp-validation-for="Email" class="text-danger"></span>
                            </div>
                            <div class="form-group">
                                <label asp-for="Name">@Localizer["modal_name_title"]</label>
                                <input asp-for="Name" type="text" class="form-control" aria-describedby="nameHelp" placeholder="@Localizer["modal_name_placeholder"]">
                                <small id="nameHelp" class="form-text text-muted">@Localizer["modal_name_described"]</small>
                                <span asp-validation-for="Name" class="text-danger"></span>
                            </div>
                            <div class="form-group">
                                <label asp-for="Subject">@Localizer["modal_subject_title"]</label>
                                <input asp-for="Subject" type="text" class="form-control" placeholder="@Localizer["modal_subject_placeholder"]">
                                <span asp-validation-for="Subject" class="text-danger"></span>
                            </div>
                            <div class="form-group">
                                <label asp-for="Message">@Localizer["modal_message_title"]</label>
                                <input asp-for="Message" type="text" class="form-control" placeholder="@Localizer["modal_message_placeholder"]">
                                <span asp-validation-for="Message" class="text-danger"></span>
                            </div>

                        </form>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">@Localizer["modal_button_cancel"]</button>
                        <input type="submit" value="@Localizer["modal_button_submit"]" form="contact_form" class="btn btn-primary" />
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="row justify-content-center">
        <div class="col mx-auto">
            <div class="talkbubble_mobile mx-auto" style="@(regionInfo.TwoLetterISORegionName.Equals("PL") ? "width: 250px" : "width:300px;")">
                <p>@Localizer["talkbubble_text"]</p>
            </div>
        </div>
    </div>
    <div class="row justify-content-center">
        <div class="col mx-auto">
            <div class="talkbubble_mobile_arrow mx-auto mb-3"></div>
            
        </div>
    </div>
    <div class="row">
        <div class="col text-center">
            <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#sendMailModal" id="button_send_mail">@Localizer["button_send_message"]</button>
        </div>
    </div>

    <div class="row align-items-center">
        <div class="col" id="social_links_text">
            <h2 class="text-center">@Localizer["social_links_text"]</h2>
        </div>
    </div>
    <div class="row align-items-center">
        <div class="col social_buttons-links text-center">
            <ul>
                <li>
                    <a target="_blank" rel="noopener noreferrer" href="https://www.facebook.com/krzysiek.rutana"><i class="fa fa-facebook"></i></a>
                </li>
                <li>
                    <a target="_blank" rel="noopener noreferrer" href="https://www.linkedin.com/in/krzysztof-rutana-0551851bb/"><i class="fa fa-linkedin"></i></a>
                </li>
                <li>
                    <a target="_blank" rel="noopener noreferrer" href="https://github.com/krzysztofrutana"><i class="fa fa-github"></i></a>
                </li>
            </ul>
        </div>
    </div>
</div>
}
else
{
<div class="container-fluid">
    <div class="row">
        <div class="col" id="section_title">
            <h1 class="text-white display-1 text-center title">@Localizer["contact_title"]</h1>
        </div>
    </div>
    <div class="row">
        <div class="modal fade" id="sendMailModal" tabindex="-1" aria-labelledby="sendMailModalLabel" aria-hidden="true">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="sendMailModalLabel">@Localizer["modal_header"]</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <div class="modal-body">
                        <form asp-controller="Contact" asp-action="SendMail" id="contact_form">
                            <div class="form-group">
                                <label asp-for="Email">@Localizer["modal_email_title"]</label>
                                <input asp-for="Email" type="email" class="form-control" aria-describedby="emailHelp" placeholder="@Localizer["modal_email_placeholder"]">
                                <small id="emailHelp" class="form-text text-muted">@Localizer["modal_email_described"]</small>
                                <span asp-validation-for="Email" class="text-danger"></span>
                            </div>
                            <div class="form-group">
                                <label asp-for="Name">@Localizer["modal_name_title"]</label>
                                <input asp-for="Name" type="text" class="form-control" aria-describedby="nameHelp" placeholder="@Localizer["modal_name_placeholder"]">
                                <small id="nameHelp" class="form-text text-muted">@Localizer["modal_name_described"]</small>
                                <span asp-validation-for="Name" class="text-danger"></span>
                            </div>
                            <div class="form-group">
                                <label asp-for="Subject">@Localizer["modal_subject_title"]</label>
                                <input asp-for="Subject" type="text" class="form-control" placeholder="@Localizer["modal_subject_placeholder"]">
                                <span asp-validation-for="Subject" class="text-danger"></span>
                            </div>
                            <div class="form-group">
                                <label asp-for="Message">@Localizer["modal_message_title"]</label>
                                <input asp-for="Message" type="text" class="form-control" placeholder="@Localizer["modal_message_placeholder"]">
                                <span asp-validation-for="Message" class="text-danger"></span>
                            </div>

                        </form>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">@Localizer["modal_button_cancel"]</button>
                        <input type="submit" value="@Localizer["modal_button_submit"]" form="contact_form" class="btn btn-primary" />
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="row align-items-center">
        <div class="col text-center ml-12" style="justify-content: right;">
            <div class="talkbubble" style="@(regionInfo.TwoLetterISORegionName.Equals("PL") ? "width: 300px" : "width:400px;")">
                <p class="mt-auto">@Localizer["talkbubble_text"]</p>
            </div>
        </div>
        <div class="col text-left m-0">
            <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#sendMailModal" id="button_send_mail">@Localizer["button_send_message"]</button>
        </div>
    </div>

    <div class="row align-items-center">
        <div class="col" id="social_links_text">
            <h2 class="text-center">@Localizer["social_links_text"]</h2>
        </div>
    </div>
    <div class="row align-items-center">
        <div class="col social_buttons-links text-center">
            <ul>
                <li>
                    <a target="_blank" rel="noopener noreferrer" href="https://www.facebook.com/krzysiek.rutana"><i class="fa fa-facebook"></i></a>
                </li>
                <li>
                    <a target="_blank" rel="noopener noreferrer" href="https://www.linkedin.com/in/krzysztof-rutana-0551851bb/"><i class="fa fa-linkedin"></i></a>
                </li>
                <li>
                    <a target="_blank" rel="noopener noreferrer" href="https://github.com/krzysztofrutana"><i class="fa fa-github"></i></a>
                </li>
            </ul>
        </div>
    </div>
</div>
}

MyWebPage/Views/Home/Index.cshtml
@using Microsoft.AspNetCore.Mvc.Localization
@inject IViewLocalizer Localizer
@inject Wangkanai.Detection.Services.IDetectionService DetectionService

<link rel="stylesheet" href="~/css/index.css?v=2" />
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@if (DetectionService.Device.Type != Wangkanai.Detection.Models.Device.Desktop)
{
    <div id="about_mobile">
        <div class="container w-100">
            @{Html.RenderPartial("About");}
        </div>
    </div>

    <div id="list_mobile">
        <div class="container w-100">
            @await Component.InvokeAsync("Projects")
        </div>
    </div>

    <div id="contact_mobile">
        <div class="container w-100">
            @{Html.RenderPartial("Contact");}
        </div>
    </div>
}
else
{
    <div id="about">
        <div class="container w-100">
            @{Html.RenderPartial("About");}
        </div>
    </div>

    <div id="list">
        <div class="container w-100">
            @await Component.InvokeAsync("Projects")
        </div>
    </div>

    <div id="contact">
        <div class="container w-100">
            @{Html.RenderPartial("Contact");}
        </div>
    </div>
}
@{
    string message = TempData["ConfirmMsg"] as string;
    if (!String.IsNullOrEmpty(message))
    {
        <div class="modal fade" id="email_sended_succes" tabindex="-1" aria-labelledby="modalLabel" aria-hidden="true">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="modalLabel">@Localizer["message_sent"]</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <div class="modal-body">
                        @Localizer["confirm_message"]
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-primary" data-dismiss="modal">OK</button>
                    </div>
                </div>
            </div>
        </div>
        @section Scripts {
            <script>
                $('#email_sended_succes').modal('show')
            </script>
        }
        TempData.Remove("ConfirmMsg");
    }
}